### ISSUE TITLE
`/new` create the redeem script

### ISSUE THREAD

**Issue by rllola** [xanimo/dogecoin-spv-node-middleware#3]
It was discussed the other day the advantage of having the merchant (or Bob) generating the redeem script with the 2 public keys instead of just giving his public key to the client (or Alice).

See https://github.com/xanimo/dogecoin-spv-node-middleware/blob/main/src/api/address.js#L13-L17

It would be preferable to have Bob being sent in parameters of the call `/new` Alice' public key (a hex string) and her locktime (an integer) (for how long she want the payment channel open). And Bob will return the script to be used with his public key in it. He can also then generate the p2sh address and save it in his database.

```javascript
router.post('/new', (req, res) => {
  /* check we received `pubkey` and `locktime` info in the req body */
  
  /* Create script */

 /* Generate P2SH address from script and save in database */

  res.json(script_hex);
});
```

The script should be created like in here https://github.com/rllola/doge-payment-channel/blob/main/index.old.js#L36-L39

The P2SH can be generated from the script like in here https://github.com/rllola/doge-payment-channel/blob/main/index.old.js#L43-L47

**Comment by patricklodder** [comment]
Thought about this. This puts the validation on the consumer wallet implementation rather than the merchant, but the consumer is the one that funds.

If Bob creates the redeem script then Alice has to put money into something she didn't create. If there is a weakness in a wallet implementation (forgot a check) for Alice, then this can be exploited by Bob, and vice versa. Since Bob receives the crypto and then fulfills, there's a possibility to spot issues before fulfillment and cancel fulfillment. Alice has no such option because she has already funded the channel. Therefore, it's better that Alice creates the channel she funds into than Bob, as it allows her to control her own funds.

Hope that makes sense. Would like to discuss further.

**Comment by rllola** [comment]
Closing this.

To avoid putting the validation on the user wallet we won't do it this way.
